### ISSUE TITLE
Using ./scripts/build-with-polygeist.sh

### ISSUE THREAD

**Issue by ilia-cher** [kumasento/polymer#126]
Hi, running ./scripts/build-with-polygeist.sh script on a clean checkout results in this error:
```
>>> Update and build Polygeist

   The Polygeist version: e5b8b83312c7a5f6fd94ea1a2cda87e54c4451fd

>>> Cloning and checkout Polygeist ...
From https://github.com/wsmoses/Polygeist
 * branch                      e5b8b83312c7a5f6fd94ea1a2cda87e54c4451fd -> FETCH_HEAD
HEAD is now at e5b8b83312c7 Fix layout top-level comment
>>> Linking Polymer to Polygeist ...
rm: /Users/e/polymer/scripts/../../Polygeist-polymer/mlir/tools/polymer: No such file or directory
```

(In addition, it seems there's also no mention of BUILD_POLYMER in polygeist build options.)

**Comment by kumasento** [comment]
Hi @ilia-cher 

Thanks for reporting this issue. `build-with-polygeist` hasn't been maintained for a while, and it doesn't reflect what the current project structure is. I'm going to fix this soon, meanwhile, if you're in a hurry, please consult the `.github/workflow/buildAndTest.yml` to see what the latest build instructions are. Thanks.

**Comment by ilia-cher** [comment]
@kumasento thanks for the prompt reply and a PR fix!
